ci:
  autoupdate_schedule: monthly
  autofix_commit_msg: pre-commit auto-fixes
  autoupdate_commit_msg: pre-commit autoupdate

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [--fix]
        exclude: (^tasks/(?!.*/src/).*|^reports/afm/)

      - id: ruff-format
        exclude: (^tasks/(?!.*/src/).*|^reports/afm/)

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: (^tasks/(?!.*/src/).*|^reports/afm/)
      - id: trailing-whitespace
        exclude: (^tasks/(?!.*/src/).*|^reports/afm/)

  - repo: https://github.com/adamchainz/blacken-docs
    rev: 1.18.0
    hooks:
      - id: blacken-docs
        exclude: ^tasks/(?!.*/src/).*

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.8.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
