name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.9"]
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      # - uses: pdm-project/setup-pdm@v3
      #   name: Set up PDM
      #   with:
      #     python-version: ${{ matrix.python-version }}
      #     cache: true

      - name: Set up Python
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""

      - name: Install dependencies
        run: |
          pip install -e ".[dev]"
          conda install -c conda-forge openbabel -y

      - name: Test
        run: pytest tests